name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleComMicewineEmuDebug assembleComMihoyoYuanshenDebug

    - name: "Get Short SHA"
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: "Get Version"
      run: |
        echo "VERSION_COM_MICEWINE_EMU=$(echo $(cat app/build.gradle.kts | grep 'comMicewineEmu {' -A 4 | grep versionName | cut -d "=" -f 2 | sed "s/\"//g" | xargs))" >> $GITHUB_ENV
        echo "VERSION_COM_MIHOYO_YUANSHEN=$(echo $(cat app/build.gradle.kts | grep 'comMihoyoYuanshen {' -A 4 | grep versionName | cut -d "=" -f 2 | sed "s/\"//g" | xargs))" >> $GITHUB_ENV

    - name: "Create Release"
      uses: softprops/action-gh-release@v2
      with:
        name: "MiceWine Application ${{ env.VERSION_COM_MICEWINE_EMU }} and Yuanshen ${{ env.VERSION_COM_MIHOYO_YUANSHEN }} (git-${{ env.SHORT_SHA }})"
        tag_name: ${{ env.SHORT_SHA }}
        prerelease: true
        files: |
          ./app/build/outputs/apk/comMicewineEmu/debug/app-comMicewineEmu-debug.apk
          ./app/build/outputs/apk/comMihoyoYuanshen/debug/app-comMihoyoYuanshen-debug.apk